name: Remove Labels on New Push

on:
  pull_request_target:
    types: [opened, synchronize] # Trigger on PR opened or new commits pushed

jobs:
  remove_labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Grant permission to modify labels
    steps:
      - name: Remove specific labels
        run: gh pr edit ${{ github.event.pull_request.number }} --remove-label "ready,deployed"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
